file_map = {
    "abilene": "abilene.xml",
    "atlanta": "atlanta.xml",
    "brain": "brain.xml",
    "cost266": "cost266.xml",
    "dfn-bwin": "dfn-bwin.xml",
    "dfn-gwin": "dfn-gwin.xml",
    "di": "di-yuan.xml",
    "france": "france.xml",
    "geant": "geant.xml",
    "germany50": "germany50.xml",
    "giul39": "giul39.xml",
    "india35": "india35.xml",
    "janos-us": "janos-us.xml",
    "janos-us-ca": "janos-us-ca.xml",
    "newyork": "newyork.xml",
    "nobel-eu": "nobel-eu.xml",
    "nobel-germany": "nobel-germany.xml",
    "nobel-us": "nobel-us.xml",
    "norway": "norway.xml",
    "pdh": "pdh.xml",
    "pioro40": "pioro40.xml",
    "polska": "polska.xml",
    "sun": "sun.xml",
    "ta1": "ta1.xml",
    "ta2": "ta2.xml",
    "zib54": "zib54.xml"
}
